version: '3.12'

services:
  db:
    image: postgres:latest
    restart: on-failure
    expose:
      - '5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $POSTGRES_USER' ]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py csu || true && pytest && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  test:
    build: .
    command: sh -c "sleep 10 && pytest"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  celery:
    build: .
    tty: true
    command: sh -c "celery -A config worker --loglevel=INFO"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
      - db
    env_file:
      - .env

  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - '6379'

volumes:
  pg_data:
